"""
rabbit.collisions — Neutrino collision kernels.

Modules (planned)
-----------------
kernels.py            CollisionOperator protocol (abstract interface).
nu_e_scattering.py    ν_e + e± ↔ ν_e + e± (CC + NC).
                      ν_x + e± ↔ ν_x + e± (NC only).
                      Hannestad–Madsen 2D momentum reduction.
pair_processes.py     ν_α ν̄_α ↔ e⁺e⁻ annihilation/creation.
"""

from rabbit.collisions.deterministic_reference import (
    COLLISION_STATISTICAL_COEFFICIENTS,
    COLLISION_STATISTICAL_MONOMIALS,
    CollisionMomentBatchResult,
    build_fixed_collision_quadrature,
    collision_statistical_factor,
    collision_statistical_polynomial_terms,
    detailed_balance_residual,
    evaluate_nue_scattering_reference,
    evaluate_nue_scattering_reference_batch,
    evaluate_nunu_diagonal_reference,
    evaluate_nunu_diagonal_twoto2_reference,
    evaluate_nunu_diagonal_twoto2_reference_batch,
    evaluate_pair_annihilation_reference,
    evaluate_pair_annihilation_reference_batch,
)
from rabbit.collisions.pstf_contractions import (
    LocalPSTFStatisticalContractionResult,
    LocalPSTFStatisticalKernelTable,
    PSTFBilinearMatrixElementTerm,
    PSTFChannelKernelTable,
    PSTFChannelRadialGridContractionResult,
    PSTFMassMatrixElementTerm,
    PSTFMassQuarticMatrixElementTerm,
    PSTFRadialChannelKernelGrid,
    PSTFRadialInvariantPrefactorConfig,
    UniversalPSTFGeometricKernelTable,
    build_local_pstf_statistical_kernel_table,
    build_normalized_radial_momentum_delta_weight_provider,
    build_normalized_unit_direction_momentum_delta_weights,
    build_pstf_channel_kernel_table,
    build_pstf_radial_channel_kernel_grid,
    build_universal_pstf_geometric_kernel_table,
    contract_local_pstf_statistical_kernel,
    contract_pstf_channel_radial_grid,
    contract_pstf_radial_channel_kernel_grid,
)
from rabbit.collisions.pstf_process_catalog import (
    IDENTICAL_NUNU_NUMBER_ENERGY_NEUTRAL_RADIAL_SOURCE_CONTRACT,
    NUNU_NUMBER_PAIR_ENERGY_NEUTRAL_RADIAL_SOURCE_CONTRACT,
    NUNU_NUMBER_NEUTRAL_RADIAL_SOURCE_CONTRACT,
    PSTFProcessRadialCollisionResult,
    PSTFProcessRadialMomentResult,
    PSTFProcessRadialMomentWeights,
    PSTFWeakProcessDescriptor,
    build_default_supported_weak_process_catalog,
    build_default_ur_weak_process_catalog,
    build_finite_mass_pair_annihilation_process_descriptor,
    build_finite_mass_nue_scattering_process_descriptor,
    build_pstf_process_radial_channel_kernel_grid,
    build_pstf_process_radial_moment_weights,
    build_ur_nue_scattering_process_descriptor,
    build_ur_nunu_diagonal_process_descriptor,
    build_ur_nunu_pairwise_process_descriptor,
    build_ur_pair_annihilation_process_descriptor,
    compute_pstf_process_radial_moments,
    compute_pstf_process_radial_moments_preweighted,
    evaluate_pstf_process_matrix_element,
    evaluate_pstf_process_radial_collision_source,
    is_identical_nunu_process_descriptor,
    is_nunu_process_descriptor,
    pstf_process_descriptor_key,
    pstf_process_particle_mode_labels,
    project_pstf_radial_collision_source_number_energy_neutral,
    project_pstf_radial_collision_source_energy_shift_number_preserving,
    project_pstf_radial_collision_source_number_neutral,
)

__all__ = [
    "COLLISION_STATISTICAL_COEFFICIENTS",
    "COLLISION_STATISTICAL_MONOMIALS",
    "CollisionMomentBatchResult",
    "build_fixed_collision_quadrature",
    "collision_statistical_factor",
    "collision_statistical_polynomial_terms",
    "detailed_balance_residual",
    "evaluate_nue_scattering_reference",
    "evaluate_nue_scattering_reference_batch",
    "evaluate_nunu_diagonal_reference",
    "evaluate_nunu_diagonal_twoto2_reference",
    "evaluate_nunu_diagonal_twoto2_reference_batch",
    "evaluate_pair_annihilation_reference",
    "evaluate_pair_annihilation_reference_batch",
    "LocalPSTFStatisticalContractionResult",
    "LocalPSTFStatisticalKernelTable",
    "PSTFBilinearMatrixElementTerm",
    "PSTFChannelKernelTable",
    "PSTFChannelRadialGridContractionResult",
    "PSTFMassMatrixElementTerm",
    "PSTFMassQuarticMatrixElementTerm",
    "PSTFRadialChannelKernelGrid",
    "PSTFRadialInvariantPrefactorConfig",
    "PSTFProcessRadialCollisionResult",
    "PSTFProcessRadialMomentResult",
    "PSTFProcessRadialMomentWeights",
    "PSTFWeakProcessDescriptor",
    "IDENTICAL_NUNU_NUMBER_ENERGY_NEUTRAL_RADIAL_SOURCE_CONTRACT",
    "NUNU_NUMBER_PAIR_ENERGY_NEUTRAL_RADIAL_SOURCE_CONTRACT",
    "NUNU_NUMBER_NEUTRAL_RADIAL_SOURCE_CONTRACT",
    "UniversalPSTFGeometricKernelTable",
    "build_local_pstf_statistical_kernel_table",
    "build_normalized_radial_momentum_delta_weight_provider",
    "build_normalized_unit_direction_momentum_delta_weights",
    "build_default_supported_weak_process_catalog",
    "build_default_ur_weak_process_catalog",
    "build_finite_mass_pair_annihilation_process_descriptor",
    "build_finite_mass_nue_scattering_process_descriptor",
    "build_pstf_channel_kernel_table",
    "build_pstf_process_radial_channel_kernel_grid",
    "build_pstf_process_radial_moment_weights",
    "build_pstf_radial_channel_kernel_grid",
    "build_ur_nue_scattering_process_descriptor",
    "build_ur_nunu_diagonal_process_descriptor",
    "build_ur_nunu_pairwise_process_descriptor",
    "build_ur_pair_annihilation_process_descriptor",
    "build_universal_pstf_geometric_kernel_table",
    "compute_pstf_process_radial_moments",
    "compute_pstf_process_radial_moments_preweighted",
    "contract_local_pstf_statistical_kernel",
    "contract_pstf_channel_radial_grid",
    "contract_pstf_radial_channel_kernel_grid",
    "evaluate_pstf_process_matrix_element",
    "evaluate_pstf_process_radial_collision_source",
    "is_identical_nunu_process_descriptor",
    "is_nunu_process_descriptor",
    "pstf_process_descriptor_key",
    "pstf_process_particle_mode_labels",
    "project_pstf_radial_collision_source_number_energy_neutral",
    "project_pstf_radial_collision_source_energy_shift_number_preserving",
    "project_pstf_radial_collision_source_number_neutral",
]
