"""AUTO-GENERATED by scripts/cas/gen_pstf_pi3.py --emit-module. Do not edit by hand.

Exact analytic Pi^(3)(x,y) angular polynomials (plan B.F3), lambdified to numpy. The
symbolic reduction + this artifact are validated against collisions/pstf_body_frame.
angular_polynomial_n3 by tests/test_pstf_pi3_cas.py. Regenerate after changing the case
set or the generator.
"""
from __future__ import annotations
import numpy  # NumPyPrinter emits numpy.* (e.g. numpy.sqrt for irrational CG consts)

def _pi3_0_0_000_123(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_0_0_000_123(y, p1, p2, p3, p4):
    return (1,)

def _pi3_0_0_000_124(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_0_0_000_124(y, p1, p2, p3, p4):
    return (1,)

def _pi3_0_0_000_134(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_0_0_000_134(y, p1, p2, p3, p4):
    return (1,)

def _pi3_0_0_000_234(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_0_0_000_234(y, p1, p2, p3, p4):
    return (1,)

def _pi3_0_0_110_123(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*x

def _pi3c_0_0_110_123(y, p1, p2, p3, p4):
    return (0, -numpy.sqrt(3),)

def _pi3_0_0_110_124(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*x

def _pi3c_0_0_110_124(y, p1, p2, p3, p4):
    return (0, -numpy.sqrt(3),)

def _pi3_0_0_110_134(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*y

def _pi3c_0_0_110_134(y, p1, p2, p3, p4):
    return (-numpy.sqrt(3)*y,)

def _pi3_0_0_110_234(x, y, p1, p2, p3, p4):
    return -1/2*numpy.sqrt(3)*p1**2/(p2*p3) - numpy.sqrt(3)*p1*x/p3 + numpy.sqrt(3)*p1*y/p2 - 1/2*numpy.sqrt(3)*p2/p3 - 1/2*numpy.sqrt(3)*p3/p2 + (1/2)*numpy.sqrt(3)*p4**2/(p2*p3)

def _pi3c_0_0_110_234(y, p1, p2, p3, p4):
    return (-1/2*numpy.sqrt(3)*p1**2/(p2*p3) + numpy.sqrt(3)*p1*y/p2 - 1/2*numpy.sqrt(3)*p2/p3 - 1/2*numpy.sqrt(3)*p3/p2 + (1/2)*numpy.sqrt(3)*p4**2/(p2*p3), -numpy.sqrt(3)*p1/p3,)

def _pi3_0_1_011_123(x, y, p1, p2, p3, p4):
    return -1/2*numpy.sqrt(3)*p1**2/(p2*p3) - numpy.sqrt(3)*p1*x/p3 + numpy.sqrt(3)*p1*y/p2 - 1/2*numpy.sqrt(3)*p2/p3 - 1/2*numpy.sqrt(3)*p3/p2 + (1/2)*numpy.sqrt(3)*p4**2/(p2*p3)

def _pi3c_0_1_011_123(y, p1, p2, p3, p4):
    return (-1/2*numpy.sqrt(3)*p1**2/(p2*p3) + numpy.sqrt(3)*p1*y/p2 - 1/2*numpy.sqrt(3)*p2/p3 - 1/2*numpy.sqrt(3)*p3/p2 + (1/2)*numpy.sqrt(3)*p4**2/(p2*p3), -numpy.sqrt(3)*p1/p3,)

def _pi3_0_1_011_124(x, y, p1, p2, p3, p4):
    return (1/2)*numpy.sqrt(3)*p1**2/(p2*p4) - numpy.sqrt(3)*p1*p3*y/(p2*p4) - 1/2*numpy.sqrt(3)*p2/p4 + (1/2)*numpy.sqrt(3)*p3**2/(p2*p4) - 1/2*numpy.sqrt(3)*p4/p2

def _pi3c_0_1_011_124(y, p1, p2, p3, p4):
    return ((1/2)*numpy.sqrt(3)*p1**2/(p2*p4) - numpy.sqrt(3)*p1*p3*y/(p2*p4) - 1/2*numpy.sqrt(3)*p2/p4 + (1/2)*numpy.sqrt(3)*p3**2/(p2*p4) - 1/2*numpy.sqrt(3)*p4/p2,)

def _pi3_0_1_011_134(x, y, p1, p2, p3, p4):
    return -1/2*numpy.sqrt(3)*p1**2/(p3*p4) - numpy.sqrt(3)*p1*p2*x/(p3*p4) - 1/2*numpy.sqrt(3)*p2**2/(p3*p4) + (1/2)*numpy.sqrt(3)*p3/p4 + (1/2)*numpy.sqrt(3)*p4/p3

def _pi3c_0_1_011_134(y, p1, p2, p3, p4):
    return (-1/2*numpy.sqrt(3)*p1**2/(p3*p4) - 1/2*numpy.sqrt(3)*p2**2/(p3*p4) + (1/2)*numpy.sqrt(3)*p3/p4 + (1/2)*numpy.sqrt(3)*p4/p3, -numpy.sqrt(3)*p1*p2/(p3*p4),)

def _pi3_0_1_011_234(x, y, p1, p2, p3, p4):
    return -1/2*numpy.sqrt(3)*p1**2/(p3*p4) - numpy.sqrt(3)*p1*p2*x/(p3*p4) - 1/2*numpy.sqrt(3)*p2**2/(p3*p4) + (1/2)*numpy.sqrt(3)*p3/p4 + (1/2)*numpy.sqrt(3)*p4/p3

def _pi3c_0_1_011_234(y, p1, p2, p3, p4):
    return (-1/2*numpy.sqrt(3)*p1**2/(p3*p4) - 1/2*numpy.sqrt(3)*p2**2/(p3*p4) + (1/2)*numpy.sqrt(3)*p3/p4 + (1/2)*numpy.sqrt(3)*p4/p3, -numpy.sqrt(3)*p1*p2/(p3*p4),)

def _pi3_0_1_101_123(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*y

def _pi3c_0_1_101_123(y, p1, p2, p3, p4):
    return (-numpy.sqrt(3)*y,)

def _pi3_0_1_101_124(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*p1/p4 - numpy.sqrt(3)*p2*x/p4 + numpy.sqrt(3)*p3*y/p4

def _pi3c_0_1_101_124(y, p1, p2, p3, p4):
    return (-numpy.sqrt(3)*p1/p4 + numpy.sqrt(3)*p3*y/p4, -numpy.sqrt(3)*p2/p4,)

def _pi3_0_1_101_134(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*p1/p4 - numpy.sqrt(3)*p2*x/p4 + numpy.sqrt(3)*p3*y/p4

def _pi3c_0_1_101_134(y, p1, p2, p3, p4):
    return (-numpy.sqrt(3)*p1/p4 + numpy.sqrt(3)*p3*y/p4, -numpy.sqrt(3)*p2/p4,)

def _pi3_0_1_101_234(x, y, p1, p2, p3, p4):
    return (1/2)*numpy.sqrt(3)*p1**2/(p2*p4) - numpy.sqrt(3)*p1*p3*y/(p2*p4) - 1/2*numpy.sqrt(3)*p2/p4 + (1/2)*numpy.sqrt(3)*p3**2/(p2*p4) - 1/2*numpy.sqrt(3)*p4/p2

def _pi3c_0_1_101_234(y, p1, p2, p3, p4):
    return ((1/2)*numpy.sqrt(3)*p1**2/(p2*p4) - numpy.sqrt(3)*p1*p3*y/(p2*p4) - 1/2*numpy.sqrt(3)*p2/p4 + (1/2)*numpy.sqrt(3)*p3**2/(p2*p4) - 1/2*numpy.sqrt(3)*p4/p2,)

def _pi3_1_0_001_123(x, y, p1, p2, p3, p4):
    return y

def _pi3c_1_0_001_123(y, p1, p2, p3, p4):
    return (y,)

def _pi3_1_0_001_124(x, y, p1, p2, p3, p4):
    return p1/p4 + p2*x/p4 - p3*y/p4

def _pi3c_1_0_001_124(y, p1, p2, p3, p4):
    return ((p1 - p3*y)/p4, p2/p4,)

def _pi3_1_0_001_134(x, y, p1, p2, p3, p4):
    return p1/p4 + p2*x/p4 - p3*y/p4

def _pi3c_1_0_001_134(y, p1, p2, p3, p4):
    return ((p1 - p3*y)/p4, p2/p4,)

def _pi3_1_0_001_234(x, y, p1, p2, p3, p4):
    return p1/p4 + p2*x/p4 - p3*y/p4

def _pi3c_1_0_001_234(y, p1, p2, p3, p4):
    return ((p1 - p3*y)/p4, p2/p4,)

def _pi3_1_0_111_123(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*x*y

def _pi3c_1_0_111_123(y, p1, p2, p3, p4):
    return (0, -numpy.sqrt(3)*y,)

def _pi3_1_0_111_124(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*p1*x/p4 - numpy.sqrt(3)*p2*x**2/p4 + numpy.sqrt(3)*p3*x*y/p4

def _pi3c_1_0_111_124(y, p1, p2, p3, p4):
    return (0, -numpy.sqrt(3)*p1/p4 + numpy.sqrt(3)*p3*y/p4, -numpy.sqrt(3)*p2/p4,)

def _pi3_1_0_111_134(x, y, p1, p2, p3, p4):
    return -numpy.sqrt(3)*p1*y/p4 - numpy.sqrt(3)*p2*x*y/p4 + numpy.sqrt(3)*p3*y**2/p4

def _pi3c_1_0_111_134(y, p1, p2, p3, p4):
    return (-numpy.sqrt(3)*p1*y/p4 + numpy.sqrt(3)*p3*y**2/p4, -numpy.sqrt(3)*p2*y/p4,)

def _pi3_1_0_111_234(x, y, p1, p2, p3, p4):
    return -1/2*numpy.sqrt(3)*p1**3/(p2*p3*p4) - 3/2*numpy.sqrt(3)*p1**2*x/(p3*p4) + (3/2)*numpy.sqrt(3)*p1**2*y/(p2*p4) - numpy.sqrt(3)*p1*p2*x**2/(p3*p4) - 1/2*numpy.sqrt(3)*p1*p2/(p3*p4) + 2*numpy.sqrt(3)*p1*x*y/p4 - numpy.sqrt(3)*p1*p3*y**2/(p2*p4) - 1/2*numpy.sqrt(3)*p1*p3/(p2*p4) + (1/2)*numpy.sqrt(3)*p1*p4/(p2*p3) - 1/2*numpy.sqrt(3)*p2**2*x/(p3*p4) + (1/2)*numpy.sqrt(3)*p2*y/p4 - 1/2*numpy.sqrt(3)*p3*x/p4 + (1/2)*numpy.sqrt(3)*p4*x/p3 + (1/2)*numpy.sqrt(3)*p3**2*y/(p2*p4) - 1/2*numpy.sqrt(3)*p4*y/p2

def _pi3c_1_0_111_234(y, p1, p2, p3, p4):
    return (-1/2*numpy.sqrt(3)*p1**3/(p2*p3*p4) + (3/2)*numpy.sqrt(3)*p1**2*y/(p2*p4) - 1/2*numpy.sqrt(3)*p1*p2/(p3*p4) - numpy.sqrt(3)*p1*p3*y**2/(p2*p4) - 1/2*numpy.sqrt(3)*p1*p3/(p2*p4) + (1/2)*numpy.sqrt(3)*p1*p4/(p2*p3) + (1/2)*numpy.sqrt(3)*p2*y/p4 + (1/2)*numpy.sqrt(3)*p3**2*y/(p2*p4) - 1/2*numpy.sqrt(3)*p4*y/p2, -3/2*numpy.sqrt(3)*p1**2/(p3*p4) + 2*numpy.sqrt(3)*p1*y/p4 - 1/2*numpy.sqrt(3)*p2**2/(p3*p4) - 1/2*numpy.sqrt(3)*p3/p4 + (1/2)*numpy.sqrt(3)*p4/p3, -numpy.sqrt(3)*p1*p2/(p3*p4),)

def _pi3_1_1_010_123(x, y, p1, p2, p3, p4):
    return x

def _pi3c_1_1_010_123(y, p1, p2, p3, p4):
    return (0, 1,)

def _pi3_1_1_010_124(x, y, p1, p2, p3, p4):
    return x

def _pi3c_1_1_010_124(y, p1, p2, p3, p4):
    return (0, 1,)

def _pi3_1_1_010_134(x, y, p1, p2, p3, p4):
    return y

def _pi3c_1_1_010_134(y, p1, p2, p3, p4):
    return (y,)

def _pi3_1_1_010_234(x, y, p1, p2, p3, p4):
    return y

def _pi3c_1_1_010_234(y, p1, p2, p3, p4):
    return (y,)

def _pi3_1_1_100_123(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_1_1_100_123(y, p1, p2, p3, p4):
    return (1,)

def _pi3_1_1_100_124(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_1_1_100_124(y, p1, p2, p3, p4):
    return (1,)

def _pi3_1_1_100_134(x, y, p1, p2, p3, p4):
    return 1

def _pi3c_1_1_100_134(y, p1, p2, p3, p4):
    return (1,)

def _pi3_1_1_100_211(x, y, p1, p2, p3, p4):
    return x

def _pi3c_1_1_100_211(y, p1, p2, p3, p4):
    return (0, 1,)

def _pi3_1_1_100_234(x, y, p1, p2, p3, p4):
    return x

def _pi3c_1_1_100_234(y, p1, p2, p3, p4):
    return (0, 1,)

def _pi3_1_1_100_311(x, y, p1, p2, p3, p4):
    return y

def _pi3c_1_1_100_311(y, p1, p2, p3, p4):
    return (y,)

def _pi3_1_1_111_123(x, y, p1, p2, p3, p4):
    return (3/4)*p1**2/(p2*p3) + (3/2)*p1*x/p3 - 3/2*p1*y/p2 + (3/4)*p2/p3 - 3/2*x*y + (3/4)*p3/p2 - 3/4*p4**2/(p2*p3)

def _pi3c_1_1_111_123(y, p1, p2, p3, p4):
    return ((1/4)*(3*p1**2 - 6*p1*p3*y + 3*p2**2 + 3*p3**2 - 3*p4**2)/(p2*p3), (1/2)*(3*p1 - 3*p3*y)/p3,)

def _pi3_1_1_111_124(x, y, p1, p2, p3, p4):
    return -3/4*p1**2/(p2*p4) - 3/2*p1*x/p4 + (3/2)*p1*p3*y/(p2*p4) - 3/2*p2*x**2/p4 + (3/4)*p2/p4 + (3/2)*p3*x*y/p4 - 3/4*p3**2/(p2*p4) + (3/4)*p4/p2

def _pi3c_1_1_111_124(y, p1, p2, p3, p4):
    return ((1/4)*(-3*p1**2 + 6*p1*p3*y + 3*p2**2 - 3*p3**2 + 3*p4**2)/(p2*p4), (1/2)*(-3*p1 + 3*p3*y)/p4, -3/2*p2/p4,)

def _pi3_1_1_111_134(x, y, p1, p2, p3, p4):
    return (3/4)*p1**2/(p3*p4) + (3/2)*p1*p2*x/(p3*p4) - 3/2*p1*y/p4 + (3/4)*p2**2/(p3*p4) - 3/2*p2*x*y/p4 + (3/2)*p3*y**2/p4 - 3/4*p3/p4 - 3/4*p4/p3

def _pi3c_1_1_111_134(y, p1, p2, p3, p4):
    return ((1/4)*(3*p1**2 - 6*p1*p3*y + 3*p2**2 + 6*p3**2*y**2 - 3*p3**2 - 3*p4**2)/(p3*p4), (1/2)*(3*p1*p2 - 3*p2*p3*y)/(p3*p4),)

def _pi3_1_1_111_234(x, y, p1, p2, p3, p4):
    return (3/4)*p1**2*x/(p3*p4) + (3/4)*p1**2*y/(p2*p4) + (3/2)*p1*p2*x**2/(p3*p4) - 3/2*p1*p3*y**2/(p2*p4) + (3/4)*p2**2*x/(p3*p4) - 3/4*p2*y/p4 - 3/4*p3*x/p4 - 3/4*p4*x/p3 + (3/4)*p3**2*y/(p2*p4) - 3/4*p4*y/p2

def _pi3c_1_1_111_234(y, p1, p2, p3, p4):
    return ((1/4)*(3*p1**2*y - 6*p1*p3*y**2 - 3*p2**2*y + 3*p3**2*y - 3*p4**2*y)/(p2*p4), (1/4)*(3*p1**2 + 3*p2**2 - 3*p3**2 - 3*p4**2)/(p3*p4), (3/2)*p1*p2/(p3*p4),)

def _pi3_1_2_111_123(x, y, p1, p2, p3, p4):
    return -3/20*numpy.sqrt(15)*p1**2/(p2*p3) - 3/10*numpy.sqrt(15)*p1*x/p3 + (3/10)*numpy.sqrt(15)*p1*y/p2 - 3/20*numpy.sqrt(15)*p2/p3 - 1/10*numpy.sqrt(15)*x*y - 3/20*numpy.sqrt(15)*p3/p2 + (3/20)*numpy.sqrt(15)*p4**2/(p2*p3)

def _pi3c_1_2_111_123(y, p1, p2, p3, p4):
    return (-3/20*numpy.sqrt(15)*p1**2/(p2*p3) + (3/10)*numpy.sqrt(15)*p1*y/p2 - 3/20*numpy.sqrt(15)*p2/p3 - 3/20*numpy.sqrt(15)*p3/p2 + (3/20)*numpy.sqrt(15)*p4**2/(p2*p3), -3/10*numpy.sqrt(15)*p1/p3 - 1/10*numpy.sqrt(15)*y,)

def _pi3_1_2_111_124(x, y, p1, p2, p3, p4):
    return (3/20)*numpy.sqrt(15)*p1**2/(p2*p4) - 1/10*numpy.sqrt(15)*p1*x/p4 - 3/10*numpy.sqrt(15)*p1*p3*y/(p2*p4) - 1/10*numpy.sqrt(15)*p2*x**2/p4 - 3/20*numpy.sqrt(15)*p2/p4 + (1/10)*numpy.sqrt(15)*p3*x*y/p4 + (3/20)*numpy.sqrt(15)*p3**2/(p2*p4) - 3/20*numpy.sqrt(15)*p4/p2

def _pi3c_1_2_111_124(y, p1, p2, p3, p4):
    return ((3/20)*numpy.sqrt(15)*p1**2/(p2*p4) - 3/10*numpy.sqrt(15)*p1*p3*y/(p2*p4) - 3/20*numpy.sqrt(15)*p2/p4 + (3/20)*numpy.sqrt(15)*p3**2/(p2*p4) - 3/20*numpy.sqrt(15)*p4/p2, -1/10*numpy.sqrt(15)*p1/p4 + (1/10)*numpy.sqrt(15)*p3*y/p4, -1/10*numpy.sqrt(15)*p2/p4,)

def _pi3_1_2_111_134(x, y, p1, p2, p3, p4):
    return -3/20*numpy.sqrt(15)*p1**2/(p3*p4) - 3/10*numpy.sqrt(15)*p1*p2*x/(p3*p4) - 1/10*numpy.sqrt(15)*p1*y/p4 - 3/20*numpy.sqrt(15)*p2**2/(p3*p4) - 1/10*numpy.sqrt(15)*p2*x*y/p4 + (1/10)*numpy.sqrt(15)*p3*y**2/p4 + (3/20)*numpy.sqrt(15)*p3/p4 + (3/20)*numpy.sqrt(15)*p4/p3

def _pi3c_1_2_111_134(y, p1, p2, p3, p4):
    return (-3/20*numpy.sqrt(15)*p1**2/(p3*p4) - 1/10*numpy.sqrt(15)*p1*y/p4 - 3/20*numpy.sqrt(15)*p2**2/(p3*p4) + (1/10)*numpy.sqrt(15)*p3*y**2/p4 + (3/20)*numpy.sqrt(15)*p3/p4 + (3/20)*numpy.sqrt(15)*p4/p3, -3/10*numpy.sqrt(15)*p1*p2/(p3*p4) - 1/10*numpy.sqrt(15)*p2*y/p4,)

def _pi3_1_2_111_234(x, y, p1, p2, p3, p4):
    return (1/10)*numpy.sqrt(15)*p1**3/(p2*p3*p4) + (3/20)*numpy.sqrt(15)*p1**2*x/(p3*p4) - 3/20*numpy.sqrt(15)*p1**2*y/(p2*p4) - 1/10*numpy.sqrt(15)*p1*p2*x**2/(p3*p4) + (1/10)*numpy.sqrt(15)*p1*p2/(p3*p4) - 2/5*numpy.sqrt(15)*p1*x*y/p4 - 1/10*numpy.sqrt(15)*p1*p3*y**2/(p2*p4) + (1/10)*numpy.sqrt(15)*p1*p3/(p2*p4) - 1/10*numpy.sqrt(15)*p1*p4/(p2*p3) - 1/20*numpy.sqrt(15)*p2**2*x/(p3*p4) - 1/4*numpy.sqrt(15)*p2*y/p4 + (1/4)*numpy.sqrt(15)*p3*x/p4 + (1/20)*numpy.sqrt(15)*p4*x/p3 + (1/20)*numpy.sqrt(15)*p3**2*y/(p2*p4) - 1/20*numpy.sqrt(15)*p4*y/p2

def _pi3c_1_2_111_234(y, p1, p2, p3, p4):
    return ((1/10)*numpy.sqrt(15)*p1**3/(p2*p3*p4) - 3/20*numpy.sqrt(15)*p1**2*y/(p2*p4) + (1/10)*numpy.sqrt(15)*p1*p2/(p3*p4) - 1/10*numpy.sqrt(15)*p1*p3*y**2/(p2*p4) + (1/10)*numpy.sqrt(15)*p1*p3/(p2*p4) - 1/10*numpy.sqrt(15)*p1*p4/(p2*p3) - 1/4*numpy.sqrt(15)*p2*y/p4 + (1/20)*numpy.sqrt(15)*p3**2*y/(p2*p4) - 1/20*numpy.sqrt(15)*p4*y/p2, (3/20)*numpy.sqrt(15)*p1**2/(p3*p4) - 2/5*numpy.sqrt(15)*p1*y/p4 - 1/20*numpy.sqrt(15)*p2**2/(p3*p4) + (1/4)*numpy.sqrt(15)*p3/p4 + (1/20)*numpy.sqrt(15)*p4/p3, -1/10*numpy.sqrt(15)*p1*p2/(p3*p4),)

def _pi3_2_0_112_234(x, y, p1, p2, p3, p4):
    return -3/4*numpy.sqrt(3)*p1**4/(p2*p3*p4**2) - 3*numpy.sqrt(3)*p1**3*x/(p3*p4**2) + 3*numpy.sqrt(3)*p1**3*y/(p2*p4**2) - 15/4*numpy.sqrt(3)*p1**2*p2*x**2/(p3*p4**2) - 3/4*numpy.sqrt(3)*p1**2*p2/(p3*p4**2) + (15/2)*numpy.sqrt(3)*p1**2*x*y/p4**2 - 15/4*numpy.sqrt(3)*p1**2*p3*y**2/(p2*p4**2) - 3/4*numpy.sqrt(3)*p1**2*p3/(p2*p4**2) + numpy.sqrt(3)*p1**2/(p2*p3) - 3/2*numpy.sqrt(3)*p1*p2**2*x**3/(p3*p4**2) - 3/2*numpy.sqrt(3)*p1*p2**2*x/(p3*p4**2) + (9/2)*numpy.sqrt(3)*p1*p2*x**2*y/p4**2 + (3/2)*numpy.sqrt(3)*p1*p2*y/p4**2 - 9/2*numpy.sqrt(3)*p1*p3*x*y**2/p4**2 - 3/2*numpy.sqrt(3)*p1*p3*x/p4**2 + 2*numpy.sqrt(3)*p1*x/p3 + (3/2)*numpy.sqrt(3)*p1*p3**2*y**3/(p2*p4**2) + (3/2)*numpy.sqrt(3)*p1*p3**2*y/(p2*p4**2) - 2*numpy.sqrt(3)*p1*y/p2 - 3/4*numpy.sqrt(3)*p2**3*x**2/(p3*p4**2) + (3/2)*numpy.sqrt(3)*p2**2*x*y/p4**2 - 3/4*numpy.sqrt(3)*p2*p3*x**2/p4**2 - 3/4*numpy.sqrt(3)*p2*p3*y**2/p4**2 + (3/4)*numpy.sqrt(3)*p2*x**2/p3 + (1/4)*numpy.sqrt(3)*p2/p3 + (3/2)*numpy.sqrt(3)*p3**2*x*y/p4**2 - 3/2*numpy.sqrt(3)*x*y - 3/4*numpy.sqrt(3)*p3**3*y**2/(p2*p4**2) + (3/4)*numpy.sqrt(3)*p3*y**2/p2 + (1/4)*numpy.sqrt(3)*p3/p2 - 1/4*numpy.sqrt(3)*p4**2/(p2*p3)

def _pi3c_2_0_112_234(y, p1, p2, p3, p4):
    return (-3/4*numpy.sqrt(3)*p1**4/(p2*p3*p4**2) + 3*numpy.sqrt(3)*p1**3*y/(p2*p4**2) - 3/4*numpy.sqrt(3)*p1**2*p2/(p3*p4**2) - 15/4*numpy.sqrt(3)*p1**2*p3*y**2/(p2*p4**2) - 3/4*numpy.sqrt(3)*p1**2*p3/(p2*p4**2) + numpy.sqrt(3)*p1**2/(p2*p3) + (3/2)*numpy.sqrt(3)*p1*p2*y/p4**2 + (3/2)*numpy.sqrt(3)*p1*p3**2*y**3/(p2*p4**2) + (3/2)*numpy.sqrt(3)*p1*p3**2*y/(p2*p4**2) - 2*numpy.sqrt(3)*p1*y/p2 - 3/4*numpy.sqrt(3)*p2*p3*y**2/p4**2 + (1/4)*numpy.sqrt(3)*p2/p3 - 3/4*numpy.sqrt(3)*p3**3*y**2/(p2*p4**2) + (3/4)*numpy.sqrt(3)*p3*y**2/p2 + (1/4)*numpy.sqrt(3)*p3/p2 - 1/4*numpy.sqrt(3)*p4**2/(p2*p3), -3*numpy.sqrt(3)*p1**3/(p3*p4**2) + (15/2)*numpy.sqrt(3)*p1**2*y/p4**2 - 3/2*numpy.sqrt(3)*p1*p2**2/(p3*p4**2) - 9/2*numpy.sqrt(3)*p1*p3*y**2/p4**2 - 3/2*numpy.sqrt(3)*p1*p3/p4**2 + 2*numpy.sqrt(3)*p1/p3 + (3/2)*numpy.sqrt(3)*p2**2*y/p4**2 + (3/2)*numpy.sqrt(3)*p3**2*y/p4**2 - 3/2*numpy.sqrt(3)*y, -15/4*numpy.sqrt(3)*p1**2*p2/(p3*p4**2) + (9/2)*numpy.sqrt(3)*p1*p2*y/p4**2 - 3/4*numpy.sqrt(3)*p2**3/(p3*p4**2) - 3/4*numpy.sqrt(3)*p2*p3/p4**2 + (3/4)*numpy.sqrt(3)*p2/p3, -3/2*numpy.sqrt(3)*p1*p2**2/(p3*p4**2),)

def _pi3_2_2_112_134(x, y, p1, p2, p3, p4):
    return -3/28*numpy.sqrt(21)*p1**3/(p3*p4**2) - 9/28*numpy.sqrt(21)*p1**2*p2*x/(p3*p4**2) - 3/28*numpy.sqrt(21)*p1**2*y/p4**2 - 3/14*numpy.sqrt(21)*p1*p2**2*x**2/(p3*p4**2) - 3/28*numpy.sqrt(21)*p1*p2**2/(p3*p4**2) - 3/14*numpy.sqrt(21)*p1*p2*x*y/p4**2 + (3/7)*numpy.sqrt(21)*p1*p3*y**2/p4**2 + (3/28)*numpy.sqrt(21)*p1*p3/p4**2 + (3/28)*numpy.sqrt(21)*p1/p3 - 3/28*numpy.sqrt(21)*p2**3*x/(p3*p4**2) - 3/14*numpy.sqrt(21)*p2**2*x**2*y/p4**2 + (3/28)*numpy.sqrt(21)*p2**2*y/p4**2 + (3/7)*numpy.sqrt(21)*p2*p3*x*y**2/p4**2 + (3/28)*numpy.sqrt(21)*p2*p3*x/p4**2 + (3/28)*numpy.sqrt(21)*p2*x/p3 - 3/14*numpy.sqrt(21)*p3**2*y**3/p4**2 - 3/28*numpy.sqrt(21)*p3**2*y/p4**2 + (1/28)*numpy.sqrt(21)*y

def _pi3c_2_2_112_134(y, p1, p2, p3, p4):
    return (-3/28*numpy.sqrt(21)*p1**3/(p3*p4**2) - 3/28*numpy.sqrt(21)*p1**2*y/p4**2 - 3/28*numpy.sqrt(21)*p1*p2**2/(p3*p4**2) + (3/7)*numpy.sqrt(21)*p1*p3*y**2/p4**2 + (3/28)*numpy.sqrt(21)*p1*p3/p4**2 + (3/28)*numpy.sqrt(21)*p1/p3 + (3/28)*numpy.sqrt(21)*p2**2*y/p4**2 - 3/14*numpy.sqrt(21)*p3**2*y**3/p4**2 - 3/28*numpy.sqrt(21)*p3**2*y/p4**2 + (1/28)*numpy.sqrt(21)*y, -9/28*numpy.sqrt(21)*p1**2*p2/(p3*p4**2) - 3/14*numpy.sqrt(21)*p1*p2*y/p4**2 - 3/28*numpy.sqrt(21)*p2**3/(p3*p4**2) + (3/7)*numpy.sqrt(21)*p2*p3*y**2/p4**2 + (3/28)*numpy.sqrt(21)*p2*p3/p4**2 + (3/28)*numpy.sqrt(21)*p2/p3, -3/14*numpy.sqrt(21)*p1*p2**2/(p3*p4**2) - 3/14*numpy.sqrt(21)*p2**2*y/p4**2,)

def _pi3_2_2_112_234(x, y, p1, p2, p3, p4):
    return (3/28)*numpy.sqrt(21)*p1**4/(p2*p3*p4**2) + (9/28)*numpy.sqrt(21)*p1**3*x/(p3*p4**2) - 9/28*numpy.sqrt(21)*p1**3*y/(p2*p4**2) + (3/28)*numpy.sqrt(21)*p1**2*p2*x**2/(p3*p4**2) + (3/14)*numpy.sqrt(21)*p1**2*p2/(p3*p4**2) - 15/14*numpy.sqrt(21)*p1**2*x*y/p4**2 + (3/28)*numpy.sqrt(21)*p1**2*p3*y**2/(p2*p4**2) + (3/14)*numpy.sqrt(21)*p1**2*p3/(p2*p4**2) - 1/7*numpy.sqrt(21)*p1**2/(p2*p3) - 3/14*numpy.sqrt(21)*p1*p2**2*x**3/(p3*p4**2) + (9/28)*numpy.sqrt(21)*p1*p2**2*x/(p3*p4**2) - 9/14*numpy.sqrt(21)*p1*p2*x**2*y/p4**2 - 15/28*numpy.sqrt(21)*p1*p2*y/p4**2 + (9/14)*numpy.sqrt(21)*p1*p3*x*y**2/p4**2 + (15/28)*numpy.sqrt(21)*p1*p3*x/p4**2 - 5/28*numpy.sqrt(21)*p1*x/p3 + (3/14)*numpy.sqrt(21)*p1*p3**2*y**3/(p2*p4**2) - 9/28*numpy.sqrt(21)*p1*p3**2*y/(p2*p4**2) + (5/28)*numpy.sqrt(21)*p1*y/p2 - 3/28*numpy.sqrt(21)*p2**3*x**2/(p3*p4**2) + (3/28)*numpy.sqrt(21)*p2**3/(p3*p4**2) - 3/7*numpy.sqrt(21)*p2**2*x*y/p4**2 + (15/28)*numpy.sqrt(21)*p2*p3*x**2/p4**2 + (15/28)*numpy.sqrt(21)*p2*p3*y**2/p4**2 - 3/14*numpy.sqrt(21)*p2*p3/p4**2 + (3/28)*numpy.sqrt(21)*p2*x**2/p3 - 1/7*numpy.sqrt(21)*p2/p3 - 3/7*numpy.sqrt(21)*p3**2*x*y/p4**2 + (3/14)*numpy.sqrt(21)*x*y - 3/28*numpy.sqrt(21)*p3**3*y**2/(p2*p4**2) + (3/28)*numpy.sqrt(21)*p3**3/(p2*p4**2) + (3/28)*numpy.sqrt(21)*p3*y**2/p2 - 1/7*numpy.sqrt(21)*p3/p2 + (1/28)*numpy.sqrt(21)*p4**2/(p2*p3)

def _pi3c_2_2_112_234(y, p1, p2, p3, p4):
    return ((3/28)*numpy.sqrt(21)*p1**4/(p2*p3*p4**2) - 9/28*numpy.sqrt(21)*p1**3*y/(p2*p4**2) + (3/14)*numpy.sqrt(21)*p1**2*p2/(p3*p4**2) + (3/28)*numpy.sqrt(21)*p1**2*p3*y**2/(p2*p4**2) + (3/14)*numpy.sqrt(21)*p1**2*p3/(p2*p4**2) - 1/7*numpy.sqrt(21)*p1**2/(p2*p3) - 15/28*numpy.sqrt(21)*p1*p2*y/p4**2 + (3/14)*numpy.sqrt(21)*p1*p3**2*y**3/(p2*p4**2) - 9/28*numpy.sqrt(21)*p1*p3**2*y/(p2*p4**2) + (5/28)*numpy.sqrt(21)*p1*y/p2 + (3/28)*numpy.sqrt(21)*p2**3/(p3*p4**2) + (15/28)*numpy.sqrt(21)*p2*p3*y**2/p4**2 - 3/14*numpy.sqrt(21)*p2*p3/p4**2 - 1/7*numpy.sqrt(21)*p2/p3 - 3/28*numpy.sqrt(21)*p3**3*y**2/(p2*p4**2) + (3/28)*numpy.sqrt(21)*p3**3/(p2*p4**2) + (3/28)*numpy.sqrt(21)*p3*y**2/p2 - 1/7*numpy.sqrt(21)*p3/p2 + (1/28)*numpy.sqrt(21)*p4**2/(p2*p3), (9/28)*numpy.sqrt(21)*p1**3/(p3*p4**2) - 15/14*numpy.sqrt(21)*p1**2*y/p4**2 + (9/28)*numpy.sqrt(21)*p1*p2**2/(p3*p4**2) + (9/14)*numpy.sqrt(21)*p1*p3*y**2/p4**2 + (15/28)*numpy.sqrt(21)*p1*p3/p4**2 - 5/28*numpy.sqrt(21)*p1/p3 - 3/7*numpy.sqrt(21)*p2**2*y/p4**2 - 3/7*numpy.sqrt(21)*p3**2*y/p4**2 + (3/14)*numpy.sqrt(21)*y, (3/28)*numpy.sqrt(21)*p1**2*p2/(p3*p4**2) - 9/14*numpy.sqrt(21)*p1*p2*y/p4**2 - 3/28*numpy.sqrt(21)*p2**3/(p3*p4**2) + (15/28)*numpy.sqrt(21)*p2*p3/p4**2 + (3/28)*numpy.sqrt(21)*p2/p3, -3/14*numpy.sqrt(21)*p1*p2**2/(p3*p4**2),)

def _pi3_2_2_200_211(x, y, p1, p2, p3, p4):
    return (3/2)*x**2 - 1/2

def _pi3c_2_2_200_211(y, p1, p2, p3, p4):
    return (-1/2, 0, 3/2,)

def _pi3_2_2_200_411(x, y, p1, p2, p3, p4):
    return (3/2)*p1**2/p4**2 + 3*p1*p2*x/p4**2 - 3*p1*p3*y/p4**2 + (3/2)*p2**2*x**2/p4**2 - 3*p2*p3*x*y/p4**2 + (3/2)*p3**2*y**2/p4**2 - 1/2

def _pi3c_2_2_200_411(y, p1, p2, p3, p4):
    return ((1/2)*(3*p1**2 - 6*p1*p3*y + 3*p3**2*y**2 - p4**2)/p4**2, (3*p1*p2 - 3*p2*p3*y)/p4**2, (3/2)*p2**2/p4**2,)

PI3_FUNCS = {
    (0, 0, (0, 0, 0), (1, 2, 3)): _pi3_0_0_000_123,
    (0, 0, (0, 0, 0), (1, 2, 4)): _pi3_0_0_000_124,
    (0, 0, (0, 0, 0), (1, 3, 4)): _pi3_0_0_000_134,
    (0, 0, (0, 0, 0), (2, 3, 4)): _pi3_0_0_000_234,
    (0, 0, (1, 1, 0), (1, 2, 3)): _pi3_0_0_110_123,
    (0, 0, (1, 1, 0), (1, 2, 4)): _pi3_0_0_110_124,
    (0, 0, (1, 1, 0), (1, 3, 4)): _pi3_0_0_110_134,
    (0, 0, (1, 1, 0), (2, 3, 4)): _pi3_0_0_110_234,
    (0, 1, (0, 1, 1), (1, 2, 3)): _pi3_0_1_011_123,
    (0, 1, (0, 1, 1), (1, 2, 4)): _pi3_0_1_011_124,
    (0, 1, (0, 1, 1), (1, 3, 4)): _pi3_0_1_011_134,
    (0, 1, (0, 1, 1), (2, 3, 4)): _pi3_0_1_011_234,
    (0, 1, (1, 0, 1), (1, 2, 3)): _pi3_0_1_101_123,
    (0, 1, (1, 0, 1), (1, 2, 4)): _pi3_0_1_101_124,
    (0, 1, (1, 0, 1), (1, 3, 4)): _pi3_0_1_101_134,
    (0, 1, (1, 0, 1), (2, 3, 4)): _pi3_0_1_101_234,
    (1, 0, (0, 0, 1), (1, 2, 3)): _pi3_1_0_001_123,
    (1, 0, (0, 0, 1), (1, 2, 4)): _pi3_1_0_001_124,
    (1, 0, (0, 0, 1), (1, 3, 4)): _pi3_1_0_001_134,
    (1, 0, (0, 0, 1), (2, 3, 4)): _pi3_1_0_001_234,
    (1, 0, (1, 1, 1), (1, 2, 3)): _pi3_1_0_111_123,
    (1, 0, (1, 1, 1), (1, 2, 4)): _pi3_1_0_111_124,
    (1, 0, (1, 1, 1), (1, 3, 4)): _pi3_1_0_111_134,
    (1, 0, (1, 1, 1), (2, 3, 4)): _pi3_1_0_111_234,
    (1, 1, (0, 1, 0), (1, 2, 3)): _pi3_1_1_010_123,
    (1, 1, (0, 1, 0), (1, 2, 4)): _pi3_1_1_010_124,
    (1, 1, (0, 1, 0), (1, 3, 4)): _pi3_1_1_010_134,
    (1, 1, (0, 1, 0), (2, 3, 4)): _pi3_1_1_010_234,
    (1, 1, (1, 0, 0), (1, 2, 3)): _pi3_1_1_100_123,
    (1, 1, (1, 0, 0), (1, 2, 4)): _pi3_1_1_100_124,
    (1, 1, (1, 0, 0), (1, 3, 4)): _pi3_1_1_100_134,
    (1, 1, (1, 0, 0), (2, 1, 1)): _pi3_1_1_100_211,
    (1, 1, (1, 0, 0), (2, 3, 4)): _pi3_1_1_100_234,
    (1, 1, (1, 0, 0), (3, 1, 1)): _pi3_1_1_100_311,
    (1, 1, (1, 1, 1), (1, 2, 3)): _pi3_1_1_111_123,
    (1, 1, (1, 1, 1), (1, 2, 4)): _pi3_1_1_111_124,
    (1, 1, (1, 1, 1), (1, 3, 4)): _pi3_1_1_111_134,
    (1, 1, (1, 1, 1), (2, 3, 4)): _pi3_1_1_111_234,
    (1, 2, (1, 1, 1), (1, 2, 3)): _pi3_1_2_111_123,
    (1, 2, (1, 1, 1), (1, 2, 4)): _pi3_1_2_111_124,
    (1, 2, (1, 1, 1), (1, 3, 4)): _pi3_1_2_111_134,
    (1, 2, (1, 1, 1), (2, 3, 4)): _pi3_1_2_111_234,
    (2, 0, (1, 1, 2), (2, 3, 4)): _pi3_2_0_112_234,
    (2, 2, (1, 1, 2), (1, 3, 4)): _pi3_2_2_112_134,
    (2, 2, (1, 1, 2), (2, 3, 4)): _pi3_2_2_112_234,
    (2, 2, (2, 0, 0), (2, 1, 1)): _pi3_2_2_200_211,
    (2, 2, (2, 0, 0), (4, 1, 1)): _pi3_2_2_200_411,
}

PI3_XCOEFFS = {  # (L,J,ranks,legs) -> fn(y,p1,p2,p3,p4) -> (A_0, A_1, ...) ascending
    (0, 0, (0, 0, 0), (1, 2, 3)): _pi3c_0_0_000_123,
    (0, 0, (0, 0, 0), (1, 2, 4)): _pi3c_0_0_000_124,
    (0, 0, (0, 0, 0), (1, 3, 4)): _pi3c_0_0_000_134,
    (0, 0, (0, 0, 0), (2, 3, 4)): _pi3c_0_0_000_234,
    (0, 0, (1, 1, 0), (1, 2, 3)): _pi3c_0_0_110_123,
    (0, 0, (1, 1, 0), (1, 2, 4)): _pi3c_0_0_110_124,
    (0, 0, (1, 1, 0), (1, 3, 4)): _pi3c_0_0_110_134,
    (0, 0, (1, 1, 0), (2, 3, 4)): _pi3c_0_0_110_234,
    (0, 1, (0, 1, 1), (1, 2, 3)): _pi3c_0_1_011_123,
    (0, 1, (0, 1, 1), (1, 2, 4)): _pi3c_0_1_011_124,
    (0, 1, (0, 1, 1), (1, 3, 4)): _pi3c_0_1_011_134,
    (0, 1, (0, 1, 1), (2, 3, 4)): _pi3c_0_1_011_234,
    (0, 1, (1, 0, 1), (1, 2, 3)): _pi3c_0_1_101_123,
    (0, 1, (1, 0, 1), (1, 2, 4)): _pi3c_0_1_101_124,
    (0, 1, (1, 0, 1), (1, 3, 4)): _pi3c_0_1_101_134,
    (0, 1, (1, 0, 1), (2, 3, 4)): _pi3c_0_1_101_234,
    (1, 0, (0, 0, 1), (1, 2, 3)): _pi3c_1_0_001_123,
    (1, 0, (0, 0, 1), (1, 2, 4)): _pi3c_1_0_001_124,
    (1, 0, (0, 0, 1), (1, 3, 4)): _pi3c_1_0_001_134,
    (1, 0, (0, 0, 1), (2, 3, 4)): _pi3c_1_0_001_234,
    (1, 0, (1, 1, 1), (1, 2, 3)): _pi3c_1_0_111_123,
    (1, 0, (1, 1, 1), (1, 2, 4)): _pi3c_1_0_111_124,
    (1, 0, (1, 1, 1), (1, 3, 4)): _pi3c_1_0_111_134,
    (1, 0, (1, 1, 1), (2, 3, 4)): _pi3c_1_0_111_234,
    (1, 1, (0, 1, 0), (1, 2, 3)): _pi3c_1_1_010_123,
    (1, 1, (0, 1, 0), (1, 2, 4)): _pi3c_1_1_010_124,
    (1, 1, (0, 1, 0), (1, 3, 4)): _pi3c_1_1_010_134,
    (1, 1, (0, 1, 0), (2, 3, 4)): _pi3c_1_1_010_234,
    (1, 1, (1, 0, 0), (1, 2, 3)): _pi3c_1_1_100_123,
    (1, 1, (1, 0, 0), (1, 2, 4)): _pi3c_1_1_100_124,
    (1, 1, (1, 0, 0), (1, 3, 4)): _pi3c_1_1_100_134,
    (1, 1, (1, 0, 0), (2, 1, 1)): _pi3c_1_1_100_211,
    (1, 1, (1, 0, 0), (2, 3, 4)): _pi3c_1_1_100_234,
    (1, 1, (1, 0, 0), (3, 1, 1)): _pi3c_1_1_100_311,
    (1, 1, (1, 1, 1), (1, 2, 3)): _pi3c_1_1_111_123,
    (1, 1, (1, 1, 1), (1, 2, 4)): _pi3c_1_1_111_124,
    (1, 1, (1, 1, 1), (1, 3, 4)): _pi3c_1_1_111_134,
    (1, 1, (1, 1, 1), (2, 3, 4)): _pi3c_1_1_111_234,
    (1, 2, (1, 1, 1), (1, 2, 3)): _pi3c_1_2_111_123,
    (1, 2, (1, 1, 1), (1, 2, 4)): _pi3c_1_2_111_124,
    (1, 2, (1, 1, 1), (1, 3, 4)): _pi3c_1_2_111_134,
    (1, 2, (1, 1, 1), (2, 3, 4)): _pi3c_1_2_111_234,
    (2, 0, (1, 1, 2), (2, 3, 4)): _pi3c_2_0_112_234,
    (2, 2, (1, 1, 2), (1, 3, 4)): _pi3c_2_2_112_134,
    (2, 2, (1, 1, 2), (2, 3, 4)): _pi3c_2_2_112_234,
    (2, 2, (2, 0, 0), (2, 1, 1)): _pi3c_2_2_200_211,
    (2, 2, (2, 0, 0), (4, 1, 1)): _pi3c_2_2_200_411,
}
