#!/usr/bin/env python3
"""scripts/generate_identifiability_doc.py — auto-generate IDENTIFIABILITY.md.

Phase β-3 deliverable (plan §4.7). Re-runs the BBN Fisher matrix at the
fiducial point (and one off-FLRW point) and writes a markdown document
summarizing the identifiability landscape: condition numbers, eigenvalues,
principal axes, marginalized 1-σ. Wired so that
``git diff --exit-code docs/IDENTIFIABILITY.md`` after running
this script is the audit gate (Plan §9 verification protocol step 5).

Usage
-----
    JAX_PLATFORMS=cpu python scripts/generate_identifiability_doc.py

Citation: arXiv:2502.20893 (Bianchi-I bound σ/H_BBN < 0.3); Aver+ 2021
(σ_Yp = 4×10⁻³); Cooke+ 2018 (σ_DH = 3×10⁻⁷); Planck 2018 (σ_η).
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Force CPU before jax import (HIP-no-binary protection on dev systems)
os.environ.setdefault("JAX_PLATFORMS", "cpu")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import numpy as np

from rabbit.inference.fisher import (
    bbn_fisher,
    fisher_diagnostics,
    gaussian_prior_fisher,
    PARAM_NAMES,
    COND_LIKELIHOOD_BUDGET,
    COND_POSTERIOR_BUDGET,
    MIN_RANK_AT_FLRW,
)


PRIOR_SIGMAS = [0.3, 0.058 / 6.104, 0.5 / 878.4]


def _format_eig(values: np.ndarray) -> str:
    return "(" + ", ".join(f"{float(v):.3e}" for v in values) + ")"


def _format_vec(vec) -> str:
    return "(" + ", ".join(f"{float(v):+.3f}" for v in vec) + ")"


def _section_for(name: str, sigma_H_fid: float) -> list[str]:
    F, diag = bbn_fisher(
        sigma_H_fid=sigma_H_fid,
        eta_fid=6.104e-10,
        tau_n_fid=878.4,
        backend="scipy",
        correction_level=2,
        N_q=20,
        fd_eps_rel=5.0e-2 if sigma_H_fid == 0.0 else 5.0e-3,
    )
    prior_F = gaussian_prior_fisher(PRIOR_SIGMAS)
    diag_post = fisher_diagnostics(F, prior_F=prior_F)
    sigma_lik = diag.sigma_marginalized
    sigma_post = diag_post.sigma_marginalized
    out = []
    out.append(f"## {name}")
    out.append("")
    out.append(f"- **rank(F_lik)** = {diag.rank} (budget ≥ {MIN_RANK_AT_FLRW})")
    out.append(f"- **rank(F_post)** = {diag_post.rank}")
    out.append(f"- **eigenvalues(F_post)** = {_format_eig(diag_post.eigenvalues)}")
    out.append(f"- **cond(F_post)** = {diag_post.condition_number:.3e}")
    out.append("")
    out.append(f"### Marginalized 1-σ (likelihood-only)")
    for n, s in zip(PARAM_NAMES, sigma_lik):
        out.append(f"- σ({n}) = {float(s):.3e}")
    out.append("")
    out.append(f"### Marginalized 1-σ (posterior, with priors)")
    for n, s in zip(PARAM_NAMES, sigma_post):
        out.append(f"- σ({n}) = {float(s):.3e}")
    out.append("")
    out.append("### Principal axes (descending eigenvalue)")
    for k, (lam, vec) in enumerate(diag_post.informative_directions):
        out.append(f"- λ_{k} = {lam:.3e}, direction = {_format_vec(vec)}")
    out.append("")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", default=str(ROOT / "docs" / "IDENTIFIABILITY.md"),
        help="Output markdown path",
    )
    args = parser.parse_args()

    lines: list[str] = []
    lines.append("# RABBIT v2.0 Identifiability — auto-generated")
    lines.append("")
    lines.append(
        "Re-generated by ``scripts/generate_identifiability_doc.py``. "
        "Run after any change to the canonical SciPy / weak-rate / network "
        "code paths. ``git diff --exit-code`` on this file is the Plan §9 "
        "verification gate."
    )
    lines.append("")
    lines.append("**Parameters:** (Σ_H, log η, log τ_n)")
    lines.append("")
    lines.append("**Observables:** (Y_p, D/H), σ = (4×10⁻³, 3×10⁻⁷)")
    lines.append("")
    lines.append("**Priors:**")
    lines.append("- Σ_H ~ Half-Normal(0.3) — arXiv:2502.20893")
    lines.append("- log η ~ Gaussian(σ = 0.058 / 6.104) — Planck 2018 + PDG")
    lines.append("- log τ_n ~ Gaussian(σ = 0.5 / 878.4) — PDG 2024")
    lines.append("")
    lines.append(
        f"**Budgets (Plan §0, §4.1):** cond(F_lik) < {COND_LIKELIHOOD_BUDGET:.0e}; "
        f"cond(F_post) < {COND_POSTERIOR_BUDGET:.0e}; rank(F_lik) ≥ "
        f"{MIN_RANK_AT_FLRW} at FLRW; rank(F_post) = 3."
    )
    lines.append("")

    lines.append("---")
    lines.append("")

    # Two truth points: FLRW boundary (rank-degenerate) and off-FLRW.
    lines.extend(_section_for("FLRW boundary", 0.0))
    lines.extend(_section_for("Off-FLRW (Σ_H = 0.05)", 0.05))

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
